### ISSUE TITLE
DSC Base Provider: Default to correct enum casing during canonicalization

### ISSUE THREAD

**Issue by norbertstoll** [puppetlabs/ruby-pwsh#127]
## Describe the Bug
Some settings of gpregistrypolicydsc won't be applied because of a mismatch regarding case sensitivity. 

GPRegistryPolicyFileParser.psm1's submits a D**W**ord or Q**W**ord, while lower case (_Dword_, _Qword_) is expected.

## Expected Behavior
Values in GPRegistryPolicyFileParser.psm1 are submitted in correct case.

## Steps to Reproduce
hiera-config:
```yaml
---

classes:
  include:
    - 'profile::dsc::gpregistrypolicy'

profile::dsc::gpregistrypolicy::registrypolicyfile:

  # Place-holder - Description CIS-CAT etc.
  'Registry(POL) - HKLM - \Software\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators':
    dsc_valuetype: 'Dword'
    dsc_valuename: 'EnumerateAdministrators'
    dsc_valuedata: ['0']
    dsc_key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\CredUI'
    dsc_targettype: 'ComputerConfiguration'
```

```
PS C:\> puppet agent -t
Info: Using configured environment 'windows_test'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Failed to apply catalog: Parameter dsc_valuetype failed on Dsc_registrypolicyfile[Registry(POL) - HKLM - \Software\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators]: dsc_registrypolicyfile.dsc_valuetype expects an undef value or a match for Enum['Binary', 'Dword', 'ExpandString', 'MultiString', 'None', 'Qword', 'String'], got 'DWord'
PS C:\>
```

## Environment
```
mod 'puppetlabs-pwshlib', '0.8.0'
mod 'dsc-gpregistrypolicydsc', '1.2.0-0-2'
```

## Additional Context
Affected lines are 645 and 653. 
Lines 682 and 690, too - however those didn't end up in an error within my config until now.

Corrected/Working code:

```powershell
    [System.String] GetRegTypeString()
    {
        [System.String] $result = ''

        switch ($this.ValueType)
        {
            ([RegType]::REG_SZ)
            {
                $Result = 'String'
            }
            ([RegType]::REG_EXPAND_SZ)
            {
                $Result = 'ExpandString'
            }
            ([RegType]::REG_BINARY)
            {
                $Result = 'Binary'
            }
            ([RegType]::REG_DWORD)
            {
                $Result = 'Dword' # has been $Result = 'DWord' 
            }
            ([RegType]::REG_MULTI_SZ)
            {
                $Result = 'MultiString'
            }
            ([RegType]::REG_QWORD)
            {
                $Result = 'Qword' # has been $Result = 'QWord' 
            }
            default
            {
                $Result = ''
            }
        }

        return $result
    }
```

I also puppetized the gpregistrypolicy-PowerShell Module via Puppet.Dsc (0.5.0) on my own. The mismatch remains.

**Comment by norbertstoll** [comment]
Hi,

the issue still exists. The behaviour didn't change in any way.

Regards,
 Norbert

**Comment by michaeltlombardi** [comment]
@norbertstoll can you give me a minimal repro of _just_ the `dsc_registrypolicyfile` resource in a test manifest? Just to confirm, you're using the latest build of `dsc-gpregistrypolicydsc` and pwshlib `0.9.0`, right?

**Comment by michaeltlombardi** [comment]
Looking into it, this is happening because of the casing mismatch between what the PowerShell DSC Resource _says_ it wants `Dword` in it's MOF and the module file:

https://github.com/dsccommunity/GPRegistryPolicyDsc/blob/c827c541ce2888d8375091ba2e6d01640f03003b/source/DSCResources/MSFT_RegistryPolicyFile/MSFT_RegistryPolicyFile.psm1#L264

https://github.com/dsccommunity/GPRegistryPolicyDsc/blob/c827c541ce2888d8375091ba2e6d01640f03003b/source/DSCResources/MSFT_RegistryPolicyFile/MSFT_RegistryPolicyFile.schema.mof#L9

And what PowerShell _actually_ returns (`DWord`)

**Comment by norbertstoll** [comment]
An excerpt of our puppetfile:

```
mod 'puppetlabs-dsc_lite', '3.1.0'
mod 'puppetlabs-pwshlib', '0.9.0'
mod 'dsc-auditpolicydsc', '1.4.0-0-3'
mod 'dsc-gpregistrypolicydsc', '1.2.0-0-3'
mod 'dsc-securitypolicydsc', '2.10.0-0-3'
```

The manifest... 

```
class profile::dsc::gpregistrypolicy (
  $refreshregistrypolicy = {},
  $registrypolicyfile = {},
) {
  create_resources(
    'dsc_refreshregistrypolicy',
    $refreshregistrypolicy
  )
  create_resources(
    'dsc_registrypolicyfile',
    $registrypolicyfile
  )
}

```

... and an example config:
---

```
classes:
  include:
    - 'profile::dsc'
    - 'profile::dsc::gpregistrypolicy'


profile::dsc::gpregistrypolicy::registrypolicyfile:

  # Place-holder - Description CIS-CAT etc.
  'Registry(POL) - HKLM - \SOFTWARE\Policies\Microsoft\WindowsFirewall\PolicyVersion':
    dsc_valuetype: 'Dword'
    dsc_valuename: 'PolicyVersion'
    dsc_valuedata: ['541']
    dsc_key: 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall'
    dsc_targettype: 'ComputerConfiguration'
```
