### ISSUE TITLE
Error when using dsc_timeout parameter.

### ISSUE THREAD

**Issue by schlitzered** [puppetlabs/ruby-pwsh#358]
## Describe the Bug
we are trying to install sqlserver using the sqlserverdsc module, this takes quite a while, so we where trying to use dsc_timeout to adjust the timeout value like so:

FYI: we are using hiera a hiera lookup & create_resources

class doing the lookup
``` 
class profiles::sqlserverdsc::dsc_sqlsetup {
  $dsc_sqlsetup = lookup('sqlserverdsc::dsc_sqlsetup', { merge => hash, default_value => {} })
  create_resources('dsc_sqlsetup', $dsc_sqlsetup)
}
```

example hiera_data

``` 
sqlserverdsc::dsc_sqlsetup:
  MSSQLSERVER:
    dsc_action: Install
    dsc_instancename: MSSQLSERVER
    dsc_sqlsysadminaccounts:
      - 'BUILTIN\Administrators'
    dsc_features: "SQLENGINE,REPLICATION,IS,CONN" # Note: The order matters her for config validation. It will work in any order but will report a misconfig if not in the "right" order. Unsure on what determines that order beyond looking at the puppet logs.
    dsc_sourcepath: 'C:\InstallMedia\SQL 2019 Standard x64'
    dsc_timeout: 7200
```

the error
```
Error: dsc_sqlsetup[\{:name=>"MSSQLSERVER", :dsc_instancename=>"MSSQLSERVER"}]: Updating: Undefined property timeout
```

## Expected Behavior
no error should be thrown when using dsc_timeout

## Steps to Reproduce
check description

## Environment
 - Puppet agent version 7
 - Windows 2016
