### ISSUE TITLE
Metaparams should not be downcased

### ISSUE THREAD

**Issue by Clebam** [puppetlabs/ruby-pwsh#373]
## Describe the Bug
dsc_base_prodiver.rb canonicalization converts everything to downcasen including metaparams which results in a comparison failure

```
dsc_scheduled_tasks:
  'patch_management':
    dsc_ensure: 'present'
    dsc_enable: true
    #//stuff
    require: File[D:/Temp/TOTO.txt] # Note the uppercase characters
```

`Error: Failed to apply catalog: Could not find dependency File[d:/temp/toto.txt] for Dsc_scheduledtask[patch_management]`

Here the characters are downcased

## Expected Behavior
The metaparams should preserve their casing

## Steps to Reproduce
Use a require on a resource

## Environment
Windows Server 2019

## Additional Context
I pinpointed the issue to this piece of code : https://github.com/puppetlabs/ruby-pwsh/blob/main/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb#L83

It better be `r.select` so that the metaparams keep the original casing
